INSERT INTO GENRES (ID, NAME) VALUES (1, 'Fiction');
INSERT INTO GENRES (ID, NAME) VALUES (2, 'Fantasy');
INSERT INTO GENRES (ID, NAME) VALUES (3, 'Children literature');

INSERT INTO AUTHORS (ID, FIRSTNAME, LASTNAME) VALUES (1, 'Lev', 'Tolstoy');
INSERT INTO AUTHORS (ID, FIRSTNAME, LASTNAME) VALUES (2, 'Fedor', 'Dostoevsky');
INSERT INTO AUTHORS (ID, FIRSTNAME, LASTNAME) VALUES (3, 'John', 'Tolkien');
INSERT INTO AUTHORS (ID, FIRSTNAME, LASTNAME) VALUES (4, 'Joanne', 'Rawlings');
INSERT INTO AUTHORS (ID, FIRSTNAME, LASTNAME) VALUES (5, 'Grimm', 'Brothers');
INSERT INTO AUTHORS (ID, FIRSTNAME, LASTNAME) VALUES (6, 'Nikolay', 'Nosov');

INSERT INTO BOOKS (ID, TITLE, AUTHOR_ID, GENRE_ID) VALUES (1, 'War and Peace', 1, 1);
INSERT INTO BOOKS (ID, TITLE, AUTHOR_ID, GENRE_ID) VALUES (2, 'Anna Karenina', 1, 1);
INSERT INTO BOOKS (ID, TITLE, AUTHOR_ID, GENRE_ID) VALUES (3, 'Crime and Punishment', 2, 1);
INSERT INTO BOOKS (ID, TITLE, AUTHOR_ID, GENRE_ID) VALUES (4, 'The Lord of the Rings', 3, 2);
INSERT INTO BOOKS (ID, TITLE, AUTHOR_ID, GENRE_ID) VALUES (5, 'Harry Potter', 5, 3);
INSERT INTO BOOKS (ID, TITLE, AUTHOR_ID, GENRE_ID) VALUES (6, 'Nesnaika', 6, 3);

