logging:
  level:
    root: INFO

spring:
  main:
    allow-circular-references: true
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

library:
  languages:
    - en
    - ru
